name: waze_research
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.3
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - scipy=1.13.1
  - scikit-learn=1.5.2
  - xgboost=2.1.2
  - ipykernel=6.29.5
